name: ci 

on:
  push:

jobs:
  build-analyse-tool:
    name: "Build analyse tool"
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout code
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # ratchet:actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Use Devenv Cache
        uses: cachix/cachix-action@v12
        with:
          name: devenv

      - name: Install Devenv
        run: nix-env -if https://github.com/cachix/devenv/tarball/latest

      - name: Cargo test
        run: devenv shell cargo test

      - name: Cargo build
        run: devenv shell cargo build --release

      - name: Test executable 
        run: |
          ./target/release/analyse-changed-groups-repos --help
